img = imread('DJI_0027_Compressed.png');
newimg2 = uint8(ImageDiffer_Log(img(:,:,1), img(:,:,2))*255);
newimg = uint8(ImageDiffer_Minus(img(:,:,1), img(:,:,2))*255);
dimg = ImageDiffer(img(:,:,1), img(:,:,2), 0.5);
figure;
subplot(1, 2, 1);
imshow(newimg);
title('I_1=1-min(\mu_1/\mu_2, \mu_2/\mu_1)');
subplot(1, 2, 2);
imshow(newimg2);
title('I_2=|log(X_1)-log(X_2)|');
imwrite(newimg, '../../Document/figure/DJI_0027_Minus_Differ.png');
imwrite(newimg2, '../../Document/figure/DJI_0027_Log_Differ.png');
figure;
imshow(dimg);
title('Mixed Differ Image');
imwrite(dimg, '../../Document/figure/DJI_0027_Differ.png');